##
## Configuration to `make clean` all plugins listed below
##
plugin_groups:
  - plugin_group:
    ## Runtime
    - path: runtime
    ## Core Plugins
    - path: timewarp_gl
    - name: audio
      path:
        git_repo: https://github.com/ILLIXR/audio_pipeline.git
        version: "1.0"
    - name: hologram
      path:
        git_repo: https://github.com/ILLIXR/HOTlab.git
        version: "1.0"
    ## Real-Time SLAM Plugins
    - path: offline_imu_cam
    - path: zed
    - name: Kimera-VIO
      path:
        git_repo: https://github.com/ILLIXR/Kimera-VIO
        version: "1.0"
    - name: OpenVINS
      path:
        git_repo: https://github.com/ILLIXR/open_vins.git
        #version: "1.0"
        version: c6a4f8835851d21f87add38260e73df63c6354a1
    - path: gtsam_integrator
    - path: pose_prediction
    ## Other Plugins
    - path: realsense
    - path: ground_truth_slam
    - path: gldemo
    - path: debugview
    - path: pose_lookup
    - path: rk4_integrator
    - path: timewarp_gl

action:
  name: clean

## Unused definitions
profile: opt
data: data
demo_data: demo_data
enable_offload: False
enable_alignment: False
