plugin_group:
  - path: timewarp_gl/
  - name: audio
    path:
      git_repo: https://github.com/ILLIXR/audio_pipeline.git
      version: 846196a4ebbf7be084b6e5f1d20f709d26bb75f4
  # - name: hologram
  #   path:
  #     git_repo: https://github.com/ILLIXR/HOTlab.git
  #     version: 51b8ef86cb1efa1204cb4a33dfaf15bb09d66903
